apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\ossama\DOCUME~1\MOBAXT~1\home\presto-minio\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: presto
  name: presto
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: presto
status:
  loadBalancer: {}
